systemlist:
  none: "いろんなことに興味があります。"
  Go: "あなたはGoのエクスパート。開発環境はLinuxMint21.3、実行環境はubuntu server 24.04.2 LTS、Go1.25.5、net/http+go-template、DBはMySQL Ver 8.0.41-0をgorpでアクセス、JavaScriptはかんたんなものに使って、複雑なもの処理量の多いものはgoのWebAssemblyにしたい。"
  ESP32: "LinuxMint21.3上でvscode+PlatformIO+ESP-IDFを使ってプログラムを開発します。ただしESP32forthだけはArduino IDEでコンパイルしています。ボードはESP32-WROOM32とESP32-S3です。"
  Arduino: "あなたは Arduino のエキスパート。開発にはvscode+PlatformIOを使っています。"
  OPi: "あなたは Orange Pi Zero 3のエキスパート。OSはArmbianで開発はGo 1.25.5 + 1 Periph.io(LinuxMint vscodeでクロスコンパイル、delveでデバッグ)を使っています。"

venderlist:
  Google:
    evapi: "GOOGLE_API_KEY"
    apikey: ""
    url: "https://generativelanguage.googleapis.com/v1beta/models/"
  Anthropic:
    evapi: "CLAUDE_API_KEY"
    apikey: ""
    url: "https://api.anthropic.com/v1/messages"
  DeepSeek:
    evapi: "DEEPSEEK_API_KEY"
    apikey: ""
    url: "https://api.deepseek.com/v1/chat/completions"
  OpenAI:
    evapi: "OPENAI_API_KEY"
    apikey: ""
    url: "https://api.openai.com/v1/chat/completions"

modellist:
  gemini-2.0-flash:
    model: "gemini"
    vendor: "Google"
  gemini-2.5-flash:
    model: "gemini"
    vendor: "Google"
  gemini-2.5-flash-lite-preview-09-2025:
    model: "gemini"
    vendor: "Google"
  gemini-2.5-pro:
    model: "gemini"
    vendor: "Google"
  gemini-3-flash-preview:
    model: "gemini"
    vendor: "Google"
  claude-opus-4-5-20251101:
    model: "claude"
    vendor: "Anthropic"
  claude-sonnet-4-5-20250929:
    model: "claude"
    vendor: "Anthropic"
  claude-haiku-4-5-20251001:
    model: "claude"
    vendor: "Anthropic"
  claude-sonnet-4-20250514:
    model: "claude"
    vendor: "Anthropic"
  claude-3-haiku-20240307:
    model: "claude"
    vendor: "Anthropic"
  deepseek-chat:
    model: "openai"
    vendor: "DeepSeek"
  deepseek-reasoner:
    model: "openai"
    vendor: "DeepSeek"
  deepseek-reasoner:
    model: "openai"
    vendor: "DeepSeek"
  gpt-4o-mini-2024-07-18:
    model: "openai"
    vendor: "OpenAI"
  o3-mini-2025-01-31:
    model: "openai2"
    vendor: "OpenAI"
  gpt-4o-2024-08-06:
    model: "openai"
    vendor: "OpenAI"
